config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :admin do
    resources :product_orders
    resources :orders do
      collection do
        get 'measure', to: 'orders#measure'
      end
    end
    resources :categories
    resources :products
  end
  get "admin" => "admin/products#index", turbo_link: false
  # root to: "admin#index"
  # get "admin" => "admin#index"
  root 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/order.rb
require 'prettyprint'

class Order < ApplicationRecord

  belongs_to :user, dependent: :destroy, inverse_of: :orders

  has_many :product_orders, dependent: :destroy, inverse_of: :order
  has_many :products, through: :product_orders

  accepts_nested_attributes_for :product_orders, allow_destroy: true
  enum status: { canceled: -1, pending: 0, success: 1 }

  validates :status, inclusion: { in: statuses.keys, message: "Trạng thái đơn hàng không hợp lệ" }
  validates :user_id, presence: { message: " user  không được để trống" }

  self.canceled
  self.success
  self.pending

  scope :sort_by_id, -> (query) {
    if query == "desc" || query == "asc"
      order(id: query)
    else
      raise ArgumentError, "query must be 'asc' or desc"
    end

  }

  scope :search_by_user_name, -> (search) {

    user_ids = User.all.where("email LIKE ?", "%#{search}%").pluck(:id)
    where(user_id: user_ids)

  }

  scope :filter_by_status, -> (status) {

    if status.in?(statuses.keys)
      where(status: status)
    else
      raise ArgumentError, "Invalid status value"
    end

  }

  scope :revenue_by_day, ->(dayParam = 1) {
    @result = select('sum(product_orders.quantity * products.price) AS total_revenue')
                .joins(:product_orders)
                .joins(:products)
                .where.not(status: Order.statuses[:canceled])
                .where(order_date: dayParam.days.ago..Time.zone.now.end_of_day)
    total_revenue = @result.first&.[](:total_revenue)
  }

  scope :number_was_sold_day, ->(dayParam = 1) {

    @result = joins(:product_orders)
                .where.not(status: Order.statuses[:canceled])
                .where(order_date: dayParam.days.ago..Time.zone.now.end_of_day)
                .sum('product_orders.quantity')

  }

  def total_price
    product_orders.joins(:product)
                  .sum { |product_order| product_order.product.price * product_order.quantity }
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  include Pagy::Backend
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :active_navlink, :handle_measure

  # GET /admin/orders or /admin/orders.json
  def measure

    render "measure"

  end

  def index
    @orders = Order.all

    @sort_id_query = params[:sort_id]
    @filter_status_query = params[:status]
    @search_query = params[:search_query]

    unless @sort_id_query.nil?
      @orders = @orders.sort_by_id(@sort_id_query)
    end
    unless @search_query.nil?
      @orders = @orders.search_by_user_name(@search_query)
    end

    unless @filter_status_query.nil?
      @orders = @orders.filter_by_status(@filter_status_query)
    end

    @pagy, @orders = pagy(@orders, items: 2)

  rescue Pagy::OverflowError
    params[:page] = 1
    retry
  end

  # GET /admin/orders/1 or /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders or /admin/orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        # @order.image_blob.attach(params[:product][:image_blob])
        format.html { redirect_to new_admin_order_url(Order.new), flash: { success: "Tạo Dơn Hàng Thành Công." } }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1 or /admin/orders/1.json
  def update

    pp order_params_for_update

    respond_to do |format|

      if @order.update(order_params_for_update)

        format.html { redirect_to admin_orders_url, flash: { success: "Cập Nhật Đơn Hàng Thành Công." } }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1 or /admin/orders/1.json
  def destroy
    pp @order
    @order.delete
    respond_to do |format|
      format.html { redirect_to admin_orders_url, flash: { success: "Xóa Sản Phẩm Thành Công." } }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.fetch(:order, {}).permit(:order_date, :user_id, :status)
  end

  def order_params_for_update
    params
      .fetch(:order, {})
      .permit(:order_date, :user_id, :status,
              product_orders_attributes: [:id, :quantity, :product_id, :order_id])
  end

  def active_navlink
    session[:active_navlink] = "orders"
  end

  def handle_measure
    @number_was_sold_day = Order.number_was_sold_day
    @number_was_sold_day_in_7_day = Order.number_was_sold_day(7)
    @revenue_today = Order.revenue_by_day(2)
    @revenue_7_day = Order.revenue_by_day(7)

  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper

  include Pagy::Frontend
end

app/views/admin/orders/_form.html.erb
<%= simple_form_for [:admin, @order] do |form| %>


  <div class="mb-4">

    <label for="exampleFormControlInput1" class="form-label">Tên Khách Hàng</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" value="<%= @order.user.email %>" readonly>


  </div>


  <div class="mb-4">
    <label for="exampleFormControlInput1" class="form-label">Giá Trị Đơn Hàng</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" value="<%= format_price(@order.total_price) %>" readonly>
  </div>





  <ul class="px-5">
    <%= form.simple_fields_for :product_orders do |product_orders_form| %>
      <li>

        <div class="mb-4">

          <div class="card">
            <h5 class="card-header fs-6 fw-semibold"><%= product_orders_form.object.product.title %></h5>
            <div class="card-body">
              <div class="my-2">


                <%= product_orders_form.input :quantity, as: :integer, input_html: { class: 'form-control', id: :price },
                                              label: 'Số Lượng', label_html: { class: "form-label" }, wrapper_html: { class: 'my-2' }, required: false %>
              </div>
              <div class="my-2">
                <div class="mb-3">
                  <label class="form-label">Giá Sản Phẩm</label>
                  <input class="form-control" readonly value="<%= format_price(product_orders_form.object.product.price) %>"/>
                </div>
              </div>
            </div>
          </div>
        </div>


      </li>
    <% end %>
  </ul>

  <div class="mb-4">
    <label for="" class="form-label">Trạng Thái Đơn Hàng</label>

    \


    <%= form.collection_select :category_id, Order.statuses, :first, :first, { prompt: "Chọn Trạng Thái Đơn Hàng",
                                                                               selected: @order.status.to_sym }, { class: "form-select ", 'data-id': 'my-select', 'data-toggle': 'tooltip', id: "my-id" } %>


  </div>



  <div class="d-flex justify-content-center">
    <%= form.submit "Sửa Đơn Hàng", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>">
</div>

app/views/admin/orders/edit.html.erb
<h3 class="title text-center fs-1  ">
  Cập Nhật Đơn Hàng
</h3>

<div class="main mt-3">

  <%= render "form", order: @order %>
  <br>


</div>

app/views/admin/orders/index.html.erb
<!--<div class="w-full text-center my-8">-->
<%#= button_to "Load stuff!", measure_admin_orders_path, method: :get, class: "yellow", data: { turbo_stream: true } %>
<!--</div>-->

<!--<div class="my-8 w-full mx-auto" id="content">-->
<!--  <h1 style="color: red">this is steam 1</h1>-->
<!--</div>-->



<div class="measure-order">

  <div class="row">
    <div class="col-lg-3">
      <div class="card text-white mb-3 rounded-4" style="max-width: 18rem;background-image: -webkit-linear-gradient(90deg, #3f5efb 0%, #fc466b 100%)"
      >
        <div class="card-body d-flex  align-items-center">
           <span>
           <i class="bi bi-currency-dollar fs-2"></i>
          </span>
          <div class="row ms-1">
            <div class="fs-6 fw-bold mb-2 text-white-50"> Doanh Thu Hôm Nay</div>
            <div class="fw-light fs-4"><%= !@revenue_today.present? ? 0 : @revenue_7_day %></div>

          </div>
        </div>
      </div>

    </div>
    <%= console %>

    <div class="col-lg-3">
      <div class="card text-white mb-3 rounded-4" style="background-image: -webkit-linear-gradient(90deg, #11998e 0%, #38ef7d 100%)"
      >
        <div class="card-body d-flex  align-items-center">
           <span>
           <i class="bi bi-calendar-week-fill fs-2"></i>

          </span>
          <div class="row ms-1">
            <div class="fs-6 fw-bold mb-2 text-white-50"> Doanh Thu Tuần</div>
            <div class="fw-light fs-4">   <%= !@revenue_7_day.present? ? 0 : @revenue_7_day %></div>

          </div>
        </div>
      </div>

    </div>
    <div class="col-lg-3">
      <div class="card text-white mb-3 rounded-4" style="    background-image: -webkit-linear-gradient(90deg, #45b649 0%, #dce35b 100%);)"
      >
        <div class="card-body d-flex  align-items-center">
           <span>
           <i class="bi bi-basket3-fill fs-2"></i>

          </span>
          <div class="row ms-1">
            <div class="fs-6 fw-bold mb-2 text-white-50"> Đơn Hàng Hôm Nay</div>
            <div class="fw-light fs-4"> <%= @number_was_sold_day %></div>

          </div>
        </div>
      </div>

    </div>

    <div class="col-lg-3">
      <div class="card text-white mb-3 rounded-4" style=";background-image: -webkit-linear-gradient(90deg, #ee0979 0%, #ff6a00 100%)"
      >
        <div class="card-body d-flex  align-items-center">
           <span>

           <i class="bi bi-activity fs-2"></i>
          </span>
          <div class="row ms-1">
            <div class="fs-6 fw-bold mb-2 text-white-50"> Đơn Hàng Tuần</div>
            <div class="fw-light fs-4"> <%= @number_was_sold_day_in_7_day %></div>

          </div>
        </div>
      </div>


    </div>

  </div>
</div>
<div class="main  ">


  <h3 class="title text-center fs-1  ">

    Đơn Hàng
  </h3>

  <div class="filter mb-4 row justify-content-xl-between mt-3">
    <div class="col-lg-2">

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Lọc Theo
        </button>
        <ul class="dropdown-menu">

          <li>
            <%= link_to "Từ Cũ Tới Mới", url_for(sort_id: 'asc'), class: "dropdown-item" %>


          </li>
          <li>
            <%= link_to "Từ Mới Tới Cũ", url_for(sort_id: 'desc'), class: "dropdown-item" %>


          </li>

        </ul>


      </div>
    </div>

    <div class="col-lg-2">

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Trạng Thái Đơn Hàng
        </button>
        <ul class="dropdown-menu">
          <% Order.statuses.each do |key, value| %>
            <li>
              <%= link_to format_status(key), url_for(status: key), class: "dropdown-item" %>
            </li>
          <% end %>


        </ul>


      </div>
    </div>


    <!--    <div class="col-lg-3">-->

    <%#= link_to new_admin_order_path, class: "btn btn-primary d-inline-block" do %>
    <!--         <span>-->
    <!--           Thêm Đơn Hàng-->
    <!--         </span>-->
    <%# end %>
    <!--    </div>-->
    <div class="col-lg-3 ">

      <form action="<%= url_for(request.parameters.merge(search_query: "")) %>" method="get">
        <div class="input-group input-group-sm ">
          <input type="text" class="form-control py-2" placeholder="Tìm Kiếm Người Mua" aria-label="Search"

                 value="<%= params[:search_query] %>" name="search_query" aria-describedby="basic-addon1">
          <button type="submit" class="input-group-text text-white bg-primary font" id="basic-addon1">
            <i class="bi bi-search fw-bold text-white"></i></button>
        </div>
      </form>

    </div>

  </div>
  <table class="table table-striped table-hover table-responsive-lg">
    <thead class="table-dark">
    <tr>
      <th scope="col">#</th>

      <th scope="col">Tên Người Đặt</th>
      <th scope="col">Trạng Thái</th>

      <th scope="col">Ngày Đặt</th>
      <th scope="col">Giá Trị</th>
      <th scope="col">Hành Động</th>
    </tr>
    </thead>
    <tbody class="table-group-divider">
    <% @orders.each_with_index do |order, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>


        <td class="">
          <%= order.user.email %>
        </td>


        <td class="">
          <div><%= format_status(order.status) %></div>
        </td>

        <td class="">
          <%= format_date_time1(order.order_date) %>
        </td>

        <td class="">

          <%= format_price(order.total_price) %>
        </td>
        <td>
          <div class="d-flex ">

            <%= link_to edit_admin_order_path(order.id), class: "btn btn-primary" do %>
              <i class="bi bi-gear-fill"></i>
            <% end %>

            <%= button_to admin_order_path(order), method: :delete, class: "btn btn-danger " do

            %>
              <i class="bi bi-trash-fill "></i>
            <% end %>


          </div>
        </td>
      </tr>

    <% end %>


    </tbody>
  </table>


  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>


</div>

app/views/admin/orders/measure.turbo_stream.erb
<!--=target="content-->
<%= turbo_stream.update "content" do %>
  <h1 style="color: red">this is steam 3</h1>
<% end %>

<%#= turbo_stream.update "content" do %>
<!--  <h1 style="color: red">this is steam 3</h1>-->
<%# end %>

app/views/admin/orders/new.html.erb
<h3 class="title text-center fs-1  ">

  Tạo Đơn Hàng
</h3>

<div class="main mt-3">

  <%= render "form", order: @order %>
  <br>


</div>

app/views/admin/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_order %>

<div>
  <%= link_to "Edit this order", edit_admin_order_path(@admin_order) %> |
  <%= link_to "Back to orders", admin_orders_path %>

  <%= button_to "Destroy this order", @admin_order, method: :delete %>
</div>