config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :admin do
    resources :product_orders
    resources :orders do
      collection do
        get 'measure', to: 'orders#measure'
      end
    end
    resources :categories
    resources :products
  end
  get "admin" => "admin/products#index", turbo_link: false
  # root to: "admin#index"
  # get "admin" => "admin#index"
  root 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
  # devise_for :users

  has_many :products, dependent: :destroy, inverse_of: :category
  validates :name, presence: { message: " tên không được để trống" }, length: { in: 6..20, message: "độ dài  tên tên phải từ  6-20" }
  scope :list_active, ->() { where(is_active: 1) }

  scope :sort_by_id, -> (query) {

    if query == "desc" || query == "asc"
      
      order(id: query)
    else
      raise ArgumentError, "query must be 'asc' or desc"
    end

  }
  scope :search_by_name, -> (search) {
    where("name LIKE ?", "%#{search}%")
  }

  def is_exits_and_equal_true
    (!self.is_active.nil? && self.is_active? && self.present?)
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  include Pagy::Backend
  before_action :set_admin_category, only: %i[ show edit update destroy ]
  before_action :active_navlink
  # GET /admin/categories or /admin/categories.json
  def index

    @sort_id_query = params[:sort_id]
    @sort_search_query = params[:search_query]

    @categories = Category.all

    unless @sort_id_query.nil?

      @categories = @categories.sort_by_id(@sort_id_query)
    end

    unless @sort_search_query.nil?
      @categories = @categories.search_by_name(@sort_search_query)
    end
    puts " day la thay doi commit của vinhIT "
    puts "day la nhanh commit code cuar branch cuar admin the vinh"
    puts "day la tesst tao ra conflict cua ly the vinh và chỉnh sửa bănhf rebase"

    puts "day la tesst xu li conflic chuyeen nhanh cua vinhit sau dc ddax ammend"
    puts "bo sung sau khi revert "
    puts "test git edit sau khi xaif rebase edit"
    puts "test git hub commit 1"
    @pagy, @categories = pagy(@categories, items: 2)
  end

  # GET /admin/categories/1 or /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories or /admin/categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save

        format.html { redirect_to new_admin_category_url(Category.new), flash: { notice: "Tạo Danh Mục Thành Công." } }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1 or /admin/categories/1.json
  def update
    respond_to do |format|

      if @category.update(category_params)

        format.html { redirect_to admin_categories_url, flash: { success: "Chỉnh Sủa Danh Mục Thành Công." } }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1 or /admin/categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to admin_categories_url, flash: { success: "Xóa Danh Mục Thành Công." } }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.fetch(:category, {}).permit(:name, :is_active)
  end

  def active_navlink
    session[:active_navlink] = "categories"
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">


  <h3><%= category.name %></h3>

</div>

app/views/admin/categories/_form.html.erb
<%#= form_with(model: [:admin, @category]) do |form| %>


<!--  <div class="mb-4">-->
<%#= form.label :name, "Tên Danh Mục:", class: "form-label" %>
<%#= form.text_field :name, class: "form-control", id: :name, placeholder: "Nhập Tên Danh Mục" %>
<%# @category.errors.messages[:name].each do |message| %>
<!--      <div class=" small text-danger mt-2">-->
<%#= message %>
<!--      </div>-->
<%# end %>
<!--  </div>-->



<!--<div class="mb-4">-->
<!--  <div class="form-check form-switch d-flex align-items-center">-->
<%#= form.check_box :is_active, { class: 'form-check-input', role: "switch", id: 'flexSwitchCheckDefault', checked: @category.is_exits_and_equal_true ? 'checked' : '' } %>


<%#= form.label :is_active, "Kích Hoạt", { class: "form-check-label ms-2", for: "flexSwitchCheckDefault" } %>
<!--  </div>-->
<!--</div>-->


<!--  <div class="d-flex justify-content-center">-->
<%#= form.submit "tạo danh mục", class: "btn btn-primary" %>
<!--  </div>-->
<%# end %>

<%#= console %>




<%= simple_form_for [:admin, @category] do |form| %>


  <%#= form.input :name, input_html: { class: 'form-control', id: 'name', value: " " }, label: 'Your username please', placeholder: 'nhập vào tên danh mục', wrapper_html: { class: 'mb-4' }, required: false, disabled: false, hint: 'You cannot change your username.', error_html: { id: "custom-error" } %>





  <%= form.input :name, input_html: { class: 'form-control', id: 'name' },
                 label: 'Tên Sản Phẩm', label_html: { class: "form-label" }, placeholder: 'Nhập Tên Danh mục', wrapper_html: { class: 'mb-4' } %>





  <%= form.input :is_active, as: :boolean, label: "Kích Hoạt", label_html: { class: "form-check-label ms-4 pt-1", for: "flexSwitchCheckDefault" },
                 input_html: { checked: @category.is_exits_and_equal_true ? 'checked' : '', style: 'transform: translateX(50%)' },
                 wrapper_html: { class: 'mb-4 form-check form-switch d-flex align-items-center  ps-0', role: "switch", id: 'flexSwitchCheckDefault' }

  %>



  <!--<div class="mb-4">-->
  <!--  <div class="form-check form-switch d-flex align-items-center">-->
<%#= form.check_box :is_active, { class: 'form-check-input', role: "switch", id: 'flexSwitchCheckDefault', checked: @category.is_exits_and_equal_true ? 'checked' : '' } %>


<%#= form.label :is_active, "Kích Hoạt", { class: "form-check-label ms-2", for: "flexSwitchCheckDefault" } %>
  <!--  </div>-->
  <!--</div>-->




  <div class="d-flex justify-content-center">
    <%= form.submit "tạo danh mục", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h3 class="title text-center fs-1  ">

  Chỉnh Sửa Danh Mục
</h3>

<%= render "form", product: @product %>

app/views/admin/categories/index.html.erb
<div class="main  ">


  <h3 class="title text-center fs-1  ">

    Danh Mục
  </h3>

  <div class="filter mb-4 row">
    <div class="col-lg-2">

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Lọc Theo
        </button>
        <ul class="dropdown-menu">

          <li>
            <%= link_to "Từ Cũ Tới Mới", url_for(sort_id: 'asc'), class: "dropdown-item" %>
            <%#= link_to "Giá Cao Tới Thấp", { controller: 'admin/categories', action: :index, sort_price: 'asc' }, class: "dropdown-item" %>

          </li>
          <li>
            <%= link_to "Từ Mới Tới Cũ", url_for(sort_id: 'desc'), class: "dropdown-item" %>
            <%#= link_to "Giá Cao Tới Thấp", { controller: 'admin/categories', action: :index, sort_price: 'asc' }, class: "dropdown-item" %>

          </li>

        </ul>


      </div>
    </div>


    <div class="col-lg-3">

      <%= link_to new_admin_category_path, class: "btn btn-primary d-inline-block" do %>
         <span>
           Thêm Danh Mục
         </span>
      <% end %>
    </div>
    <div class="col-lg-3 ms-auto">

      <form action="<%= url_for(request.parameters.merge(search_query: "")) %>" method="get">
        <div class="input-group input-group-sm ">
          <input type="text" class="form-control py-2" value="<%= params[:search_query] %>" placeholder="Search" aria-label="Search" name="search_query" aria-describedby="basic-addon1">
          <button type="submit" class="input-group-text text-white bg-primary font" id="basic-addon1">
            <i class="bi bi-search fw-bold text-white"></i></button>
        </div>
      </form>

    </div>

  </div>
  <table class="table table-striped table-hover table-responsive-lg">
    <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tên</th>

      <th scope="col">Kích Hoạt</th>
      <th scope="col">Hành Động</th>

    </tr>
    </thead>
    <tbody class="table-group-divider">
    <% @categories.each_with_index do |category, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td class="">
          <%= category.name %>
        </td>


        <td class="">

          <div class=" align-center">
            <i class="bi bi-check-circle-fill fs-4  <%= category.is_active? ? "text-success" : "text-secondary" %> "></i>
          </div>
        </td>

        <td>
          <div class="d-flex ">

            <%= link_to edit_admin_category_path(category.id), class: "btn btn-primary" do %>
              <i class="bi bi-gear-fill"></i>
            <% end %>

            <%= button_to admin_category_path(category.id), method: :delete, class: "btn btn-danger " do

            %>
              <i class="bi bi-trash-fill "></i>
            <% end %>


          </div>
        </td>
      </tr>

    <% end %>


    </tbody>
  </table>


  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>


</div>

app/views/admin/categories/new.html.erb
<h3 class="title text-center fs-1  ">

  Tạo Danh Mục
</h3>

<div class="main mt-3">

  <%= render "form", category: @category %>
  <br>


</div>

app/views/admin/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_category %>

<div>
  <%= link_to "Edit this category", edit_admin_category_path(@admin_category) %> |
  <%= link_to "Back to categories", admin_categories_path %>

  <%= button_to "Destroy this category", @admin_category, method: :delete %>
</div>