config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :admin do
    resources :product_orders
    resources :orders do
      collection do
        get 'measure', to: 'orders#measure'
      end
    end
    resources :categories
    resources :products
  end
  get "admin" => "admin/products#index", turbo_link: false
  # root to: "admin#index"
  # get "admin" => "admin#index"
  root 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, dependent: :destroy, inverse_of: :products
  has_many :product_orders, dependent: :destroy, inverse_of: :product
  has_many :orders, through: :product_orders
  validates :title, presence: { message: " tên không được để trống" }, length: { in: 6..30, message: "độ dài  tên tên phải từ  6-30" }
  validates :description, presence: { message: " mô tả không được để trống" }, length: { in: 6..20, message: "độ dài mô tả  tên tên phải từ  6-20" }
  validates :price, presence: { message: " giá không được để trống" }, numericality: { only_integer: true, in: 0..10000, message: "giá phải nằm trong khoảng từ 0 đến 10000" }
  validates :category_id, presence: { message: " danh mục không được để trống" }
  validates :image, presence: false

  has_one_attached :image_blob, dependent: :purge_now

  scope :list_active, ->() { where(is_active: 1) }

  scope :sort_by_price, -> (query) {
    if query == "desc" || query == "asc"
      order(price: query)
    else
      raise ArgumentError, "query must be 'asc' or desc"
    end

  }
  scope :sort_by_id, -> (query) {
    if query == "desc" || query == "asc"
      order(id: query)
    else
      raise ArgumentError, "query must be 'asc' or desc"
    end

  }
  scope :search_by_title, -> (search) {

    where("title LIKE ?", "%#{search}%")
  }

  # before_update :delete_attached_image

  def is_exits_and_equal_true
    (!self.is_active.nil? && self.is_active? && self.present?)
  end

  def delete_attached_old_image(id)
    blob_to_delete = ActiveStorage::Blob.find_by(id: id)
    if persisted? && image_blob.attached? && blob_to_delete
      blob_to_delete.purge
    end

  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  include Pagy::Backend
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :active_navlink

  # GET /admin/products or /admin/products.json
  def index

    @sort_price_query = params[:sort_price]
    @sort_id_query = params[:sort_id]
    @sort_search_query = params[:search_query]

    @products = Product.all

    unless @sort_price_query.nil?
      @products = @products.sort_by_price(@sort_price_query)
    end
    unless @sort_id_query.nil?
      @products = @products.sort_by_id(@sort_id_query)
    end

    unless @sort_search_query.nil?
      @products = @products.search_by_title(@sort_search_query)
    end

    @pagy, @products = pagy(@products, items: 4)

  rescue Pagy::OverflowError
    params[:page] = 1
    retry
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show

  end

  # GET /admin/products/new
  def new
    @product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create

    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        # @product.image_blob.attach(params[:product][:image_blob])
        format.html { redirect_to new_admin_product_url(Product.new), flash: { success: "Tạo Sản Phẩm Thành Công." } }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update

    respond_to do |format|
      @old_image = @product.image_blob.id
      if @product.update(product_params)
        @product.delete_attached_old_image(@old_image)
        format.html { redirect_to admin_products_url, flash: { success: "Chỉnh Sủa Sản Phẩm Thành Công." } }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy

    @product = Product.find(params[:id])

    if @product.image_blob.attached?
      @product.image_blob.purge
    end

    @product.delete
    respond_to do |format|
      format.html { redirect_to admin_products_url, flash: { success: "Xóa Sản Phẩm Thành Công." } }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.fetch(:product, {}).permit(:title, :price, :image_blob, :description, :category_id, :is_active)
  end

  def active_navlink
    session[:active_navlink] = "products"
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  include Pagy::Frontend

end

app/views/admin/products/_form.html.erb
<%#= form_with(model: [:admin, @product]) do |form| %>


<%# if @product.errors.any? %>
<!--    <div style="color: red">-->
<!--      <h2><%#= pluralize(@product.errors.count, "error") %> prohibited this admin_category from being saved:</h2>-->

<!--      <ul>-->
<%# @product.errors.each do |error| %>
<!--          <li><%#= error.full_message %></li>-->
<%# end %>
<!--      </ul>-->
<!--    </div>-->
<%# end %>


<!--<div class="mb-4">-->
<%#= form.label :title, "Tên Danh Mục:", class: "form-label" %>
<%#= form.text_field :title, class: "form-control", id: :title, placeholder: "Nhập Tên Sản Phẩm" %>
<%# @product.errors.messages[:title].each do |message| %>

<!--    <div class=" small text-danger mt-2">-->
<%#= message %>
<!--    </div>-->
<%# end %>
<!--</div>-->
<!--<div class="mb-4">-->
<%#= form.label :price, "Giá:", class: "form-label" %>
<%#= form.number_field :price, class: "form-control", id: :price, placeholder: "Nhập Giá" %>

<%# @product.errors.messages[:price].each do |message| %>
<!--    <div class=" small text-danger mt-2"><%#= message %></div>-->
<%# end %>
<!--</div>-->
<!--<div class="mb-4">-->
<%#= form.label :description, "Mô Tả Sản Phẩm:", class: "form-label" %>
<%#= form.text_area :description, class: "form-control", id: :description, placeholder: "Nhập Mô Tả Sản Phẩm" %>

<%# @product.errors.messages[:description].each do |message| %>
<!--    <div class=" small text-danger mt-2"><%#= message %></div>-->
<%# end %>
<!--</div>-->



<!--<div class="mb-4">-->
<!--  <div class="form-check form-switch d-flex align-items-center">-->
<%#= form.check_box :is_active, { class: "form-check-input", role: "switch", id: "flexSwitchCheckDefault", checked: @product.is_exits_and_equal_true ? "checked" : "" } %>

<%#= form.label :is_active, "Kích Hoạt", { class: "form-check-label ms-2", for: "flexSwitchCheckDefault" } %>
<!--  </div>-->
<!--</div>-->

<!--<div class="mb-4">-->


<%#= form.collection_select :category_id, Category.list_active, :id, :name, { prompt: "Open this select menu",
selected: !@product.id.nil? ? @product.category_id : Category.list_active.first[:id] }, { class: "form-select ", 'data-id': 'my-select', 'data-toggle': 'tooltip', id: "my-id" } %>


<%# @product.errors.messages[:category_id].each do |message| %>
<!--    <div class=" small text-danger mt-2"><%#= message %></div>-->
<%# end %>

<!--</div>-->

<!--<div class="mb-4">-->
<%#= form.label :image, "Tải Ảnh Lên:", class: "form-label" %>
<%#= form.file_field :image_blob, { class: "form-control", id: :image, "aria-label": "Upload" } %>



<%# if @product.image_blob.attached? && @product.image_blob.blob.present? && @product.image_blob.blob.persisted? %>
<!--    <div id="image_preview " class="mt-3">-->
<!--      <div style="">-->

<%#= image_tag @product.image_blob, { class: "object-fit-cover ", style: "width: 200px" } %>

<!--      </div>-->
<!--    </div>-->
<%# end %>

<!--</div>-->


<!--<div class="d-flex justify-content-center">-->
<%#= form.submit "tạo sản phẩm", class: "btn btn-primary" %>
<!--</div>-->
<%# end %>


<%= console %>

<%= simple_form_for [:admin, @product] do |form| %>

  <%#= form.input :name, input_html: { class: 'form-control', id: 'name', value: " " }, label: 'Your username please', placeholder: 'nhập vào tên danh mục', wrapper_html: { class: 'mb-4' }, required: false, disabled: false, hint: 'You cannot change your username.', error_html: { id: "custom-error" } %>
  <%= form.input :title, input_html: { class: 'form-control', id: 'title' }, required: false,
                 label: 'Tên Sản Phẩm', label_html: { class: "form-label" }, placeholder: 'Nhập Tên Sản Phẩm', wrapper_html: { class: 'mb-4' } %>


  <%= form.input :price, as: :integer, input_html: { class: 'form-control', id: :price },
                 label: 'Giá Sản Phẩm', label_html: { class: "form-label" }, wrapper_html: { class: 'mb-4' }, required: false %>




  <!-- select of simple form have not        wrapper_html-->


  <%= form.collection_select :category_id, Category.list_active, :id, :name, { prompt: "Chọn Danh Mục",
                                                                               selected: !@product.id.nil? ? @product.category_id : false }, { class: "form-select ", 'data-id': 'my-select', 'data-toggle': 'tooltip', id: "my-id" } %>


  <% @product.errors.messages[:category_id].each do |message| %>
    <div class=" small text-danger  "><%= message %></div>
  <% end %>




  <%= form.input :description, as: :text, input_html: { class: 'form-control', id: 'description' },
                 label: 'Mô Tả Sản Phẩm', label_html: { class: "form-label" }, placeholder: 'Nhập Mô Tả  Sản Phẩm', wrapper_html: { class: 'mb-4 mt-4' } %>






  <%= form.input :image_blob, as: :file, input_html: { class: 'form-control', id: 'title', "aria-label": "Upload" },
                 label: 'Tải Ảnh lên', label_html: { class: "form-label" }, placeholder: 'Tải Ảnh lên ở đây', wrapper_html: { class: 'mb-4' } %>


  <% if @product.image_blob.attached? && @product.image_blob.blob.present? && @product.image_blob.blob.persisted? %>
    <div id="image_preview " class="mt-3">
      <div style="">

        <%= image_tag @product.image_blob, { class: "object-fit-cover ", style: "width: 200px" } %>

      </div>
    </div>
  <% end %>


  <%= form.input :is_active, as: :boolean, label: "Kích Hoạt", label_html: { class: "form-check-label ms-4 pt-1", for: "flexSwitchCheckDefault" },
                 input_html: { checked: @product.is_active.nil? ? false : true, style: 'transform: translateX(50%)' },
                 wrapper_html: { class: 'mb-4 form-check form-switch d-flex align-items-center  ps-0', role: "switch", id: 'flexSwitchCheckDefault' }

  %>



  <div class="d-flex justify-content-center">
    <%= form.submit "tạo sản phẩm", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
</div>

app/views/admin/products/edit.html.erb
<h3 class="title text-center fs-1  ">

  Chỉnh Sửa Sản Phẩm
</h3>

<%= render "form", product: @product %>

<br>

<!--<div>-->
<!--  <%#= link_to "Show this product", @admin_product %> |-->
<%#= link_to "Back to products", admin_products_path %>


<!--</div>-->

app/views/admin/products/index.html.erb
<%# content_for :head_menu_admin do %>
<%# stylesheet_link_tag "demo1" %>
<%# end %>



<!--<p style="color: green"><%#= notice %></p>-->







<!--<div id="admin_products">-->

<!--</div>-->




<div class="main  ">


  <h3 class="title text-center fs-1  ">

    Sản Phẩm
  </h3>

  <div class="filter mb-4 row">
    <div class="col-lg-2">

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Lọc Theo
        </button>
        <ul class="dropdown-menu">
          <li>

            <%#= link_to "Giá Cao Tới Thấp", url_for(request.parameters.merge(sort_price: 'desc')), class: "dropdown-item" %>
            <%= link_to "Giá Cao Tới Thấp", url_for(sort_price: 'desc'), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "Giá Thấp Tới Thấp", url_for(sort_price: 'asc'), class: "dropdown-item" %>
          </li>
          <li>
            <%= link_to "Từ Cũ Tới Mới", url_for(sort_id: 'asc'), class: "dropdown-item" %>
            <%#= link_to "Giá Cao Tới Thấp", { controller: 'admin/products', action: :index, sort_price: 'asc' }, class: "dropdown-item" %>

          </li>
          <li>
            <%= link_to "Từ Mới Tới Cũ", url_for(sort_id: 'desc'), class: "dropdown-item" %>
            <%#= link_to "Giá Cao Tới Thấp", { controller: 'admin/products', action: :index, sort_price: 'asc' }, class: "dropdown-item" %>

          </li>

        </ul>


      </div>
    </div>


    <div class="col-lg-3">

      <%= link_to new_admin_product_path, class: "btn btn-primary d-inline-block" do %>
         <span>
           Thêm Sản Phẩm
         </span>
      <% end %>
    </div>
    <div class="col-lg-3 ms-auto">

      <form action="<%= url_for(request.parameters.merge(search_query: "")) %>" method="get">
        <div class="input-group input-group-sm ">
          <input type="text" class="form-control py-2" placeholder="Search" aria-label="Search" value="<%= params[:search_query] %>" name="search_query" aria-describedby="basic-addon1">
          <button type="submit" class="input-group-text text-white bg-primary font" id="basic-addon1">
            <i class="bi bi-search fw-bold text-white"></i></button>
        </div>
      </form>

    </div>

  </div>
  <table class="table table-striped table-hover table-responsive-lg">
    <thead class="table-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tên</th>
      <th scope="col">Giá</th>
      <th scope="col">Hình Ảnh</th>
      <th scope="col">Kích Hoạt</th>
      <th scope="col">Hành Động</th>
    </tr>
    </thead>
    <tbody class="table-group-divider">
    <% @products.each_with_index do |product, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td class="">
          <%= product.title %>
        </td>
        <td class="">
          <div><%= format_price(product.price) %></div>
        </td>
        <td class="">
          <% if product.image_blob.attached? %>
            <%= image_tag product.image_blob, class: "object-fit-cover", style: "width: 60px" %>

          <% end %>

        </td>

        <td class="">

          <div class=" align-center">
            <i class="bi bi-check-circle-fill fs-4  <%= product.is_active? ? "text-success" : "text-secondary" %> "></i>
          </div>
        </td>

        <td>
          <div class="d-flex ">

            <%= link_to edit_admin_product_path(product.id), class: "btn btn-primary" do %>
              <i class="bi bi-gear-fill"></i>
            <% end %>

            <%= button_to admin_product_path(product.id), method: :delete, class: "btn btn-danger " do

            %>
              <i class="bi bi-trash-fill "></i>
            <% end %>


          </div>
        </td>
      </tr>

    <% end %>


    </tbody>
  </table>


  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>


</div>

app/views/admin/products/new.html.erb
<%# content_for :head_menu_admin do %>
<%# stylesheet_link_tag "demo1" %>
<%# end %>



<!--<p style="color: green"><%#= notice %></p>-->




<h3 class="title text-center fs-1  ">

  Tạo Sản Phẩm
</h3>

<div class="main mt-3">

  <%= render "form", product: @product %>
  <br>


</div>

app/views/admin/products/show.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<%#= render @admin_product %>

<!--<div>-->
<!--  <%#= link_to "Edit this product", edit_admin_product_path(@admin_product) %> |-->
<%#= link_to "Back to products", admin_products_path %>

<%#= button_to "Destroy this product", @admin_product, method: :delete %>
<!--</div>-->